name: main

on:
  schedule:
    # 每周一00:00 UTC触发（北京时间周一08:00）
    - cron: '0 0 * * 1'
  workflow_dispatch:  # 允许手动触发

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run collect.py without clash check
        run: python collect.py --skip
